name: PR check + Discord

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run dummy check
        run: |
          echo "Running dummy check..."
          exit 0

      - name: Notify Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOOK }}
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            MESSAGE="✅ PR #${{ github.event.pull_request.number }} passed"
          else
            MESSAGE="❌ PR #${{ github.event.pull_request.number }} failed"
          fi

          curl -s -H "Content-Type: application/json" \
            -d "{\"content\": \"$MESSAGE\"}" \
            "$DISCORD_WEBHOOK" || true
